# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ebd/project/sharemem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ebd/project/sharemem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ebd/project/sharemem/CMakeFiles /home/ebd/project/sharemem/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ebd/project/sharemem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named send

# Build rule for target.
send: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 send
.PHONY : send

# fast build rule for target.
send/fast:
	$(MAKE) -f CMakeFiles/send.dir/build.make CMakeFiles/send.dir/build
.PHONY : send/fast

#=============================================================================
# Target rules for targets named python2share

# Build rule for target.
python2share: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 python2share
.PHONY : python2share

# fast build rule for target.
python2share/fast:
	$(MAKE) -f CMakeFiles/python2share.dir/build.make CMakeFiles/python2share.dir/build
.PHONY : python2share/fast

ApiShare_dll.o: ApiShare_dll.cpp.o

.PHONY : ApiShare_dll.o

# target to build an object file
ApiShare_dll.cpp.o:
	$(MAKE) -f CMakeFiles/python2share.dir/build.make CMakeFiles/python2share.dir/ApiShare_dll.cpp.o
.PHONY : ApiShare_dll.cpp.o

ApiShare_dll.i: ApiShare_dll.cpp.i

.PHONY : ApiShare_dll.i

# target to preprocess a source file
ApiShare_dll.cpp.i:
	$(MAKE) -f CMakeFiles/python2share.dir/build.make CMakeFiles/python2share.dir/ApiShare_dll.cpp.i
.PHONY : ApiShare_dll.cpp.i

ApiShare_dll.s: ApiShare_dll.cpp.s

.PHONY : ApiShare_dll.s

# target to generate assembly for a file
ApiShare_dll.cpp.s:
	$(MAKE) -f CMakeFiles/python2share.dir/build.make CMakeFiles/python2share.dir/ApiShare_dll.cpp.s
.PHONY : ApiShare_dll.cpp.s

receive_example.o: receive_example.cpp.o

.PHONY : receive_example.o

# target to build an object file
receive_example.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/receive_example.cpp.o
.PHONY : receive_example.cpp.o

receive_example.i: receive_example.cpp.i

.PHONY : receive_example.i

# target to preprocess a source file
receive_example.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/receive_example.cpp.i
.PHONY : receive_example.cpp.i

receive_example.s: receive_example.cpp.s

.PHONY : receive_example.s

# target to generate assembly for a file
receive_example.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/receive_example.cpp.s
.PHONY : receive_example.cpp.s

send_example.o: send_example.cpp.o

.PHONY : send_example.o

# target to build an object file
send_example.cpp.o:
	$(MAKE) -f CMakeFiles/send.dir/build.make CMakeFiles/send.dir/send_example.cpp.o
.PHONY : send_example.cpp.o

send_example.i: send_example.cpp.i

.PHONY : send_example.i

# target to preprocess a source file
send_example.cpp.i:
	$(MAKE) -f CMakeFiles/send.dir/build.make CMakeFiles/send.dir/send_example.cpp.i
.PHONY : send_example.cpp.i

send_example.s: send_example.cpp.s

.PHONY : send_example.s

# target to generate assembly for a file
send_example.cpp.s:
	$(MAKE) -f CMakeFiles/send.dir/build.make CMakeFiles/send.dir/send_example.cpp.s
.PHONY : send_example.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... send"
	@echo "... python2share"
	@echo "... ApiShare_dll.o"
	@echo "... ApiShare_dll.i"
	@echo "... ApiShare_dll.s"
	@echo "... receive_example.o"
	@echo "... receive_example.i"
	@echo "... receive_example.s"
	@echo "... send_example.o"
	@echo "... send_example.i"
	@echo "... send_example.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

